BBBB BBBB
BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
BBB BBBB BB BBBBBBBBB
BB BBBBBBBBBBBBB BB BBBBBB
 XX
BBBB
XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXXXXX XXXXXX
BBBBB X
BBBBBB
XXXXXXXXXX gettext(u'My Test to be translated') XXXXXXXXXXXX
